// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/oliverisaac/pushable/types"
)

func SignUpForm(err error) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"sign-up-form\" class=\"flex flex-col items-center justify-center h-screen\"><form hx-post=\"/auth/sign-up\" hx-target=\"body\" class=\"w-full max-w-md p-8 space-y-6 rounded-lg bg-neutral-800\"><a href=\"/\" title=\"Napp Home\" class=\"flex items-center justify-center mb-6 space-x-2 text-2xl font-bold text-white\">Pushable</a><div><label for=\"name\" class=\"block mb-2 text-sm font-bold text-neutral-400\">Name</label> <input id=\"name\" type=\"text\" name=\"name\" autocomplete=\"name\" value=\"\" required class=\"w-full px-4 py-2 text-white rounded-md bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-600\"></div><div><label for=\"email\" class=\"block mb-2 text-sm font-bold text-neutral-400\">Email</label> <input id=\"email\" type=\"text\" name=\"email\" autocomplete=\"email\" value=\"\" required class=\"w-full px-4 py-2 text-white rounded-md bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-600\"></div><div><label for=\"password\" class=\"block mb-2 text-sm font-bold text-neutral-400\">Password</label> <input id=\"password\" type=\"password\" name=\"password\" value=\"\" required class=\"w-full px-4 py-2 text-white rounded-md bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-600\"></div><button type=\"submit\" class=\"w-full px-4 py-2 text-white rounded-md bg-primary-600 hover:bg-primary-700\">Register</button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if err != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"mt-2 text-sm text-red-500\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(err.Error())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components.templ`, Line: 44, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-sm text-center text-neutral-400\">Already have an account? <button type=\"button\" hx-get=\"/auth/sign-in\" hx-target=\"body\" class=\"font-bold text-primary-400 hover:underline\">Sign In</button></p></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func SignInForm(config types.Config, err error) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"sign-in-form\" class=\"flex flex-col items-center justify-center h-screen\"><form hx-post=\"/auth/sign-in\" hx-target=\"body\" class=\"w-full max-w-md p-8 space-y-6 rounded-lg bg-neutral-800\"><a href=\"/\" title=\"Napp Home\" class=\"flex items-center justify-center mb-6 space-x-2 text-2xl font-bold text-white\">Pushable</a><div><label for=\"email\" class=\"block mb-2 text-sm font-bold text-neutral-400\">Email</label> <input id=\"email\" type=\"text\" name=\"email\" autocomplete=\"email\" value=\"\" required class=\"w-full px-4 py-2 text-white rounded-md bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-600\"></div><div><label for=\"password\" class=\"block mb-2 text-sm font-bold text-neutral-400\">Password</label> <input id=\"password\" type=\"password\" name=\"password\" value=\"\" required class=\"w-full px-4 py-2 text-white rounded-md bg-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-600\"></div><button type=\"submit\" class=\"w-full px-4 py-2 text-white rounded-md bg-primary-600 hover:bg-primary-700\">Sign In</button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if err != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"mt-2 text-sm text-red-500\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(err.Error())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components.templ`, Line: 84, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if len(config.AllowSignupEmails) > 0 || config.AllowSignup {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-sm text-center text-neutral-400\">Do you need an account? <button type=\"button\" hx-get=\"/auth/sign-up\" hx-target=\"body\" class=\"font-bold text-primary-400 hover:underline\">Register Now</button></p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
